name: Commit Workflow

on:
  push:
    branches: [Feature-123]
#test
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with: 
        java-version: 1.8
    - name: Cache Maven packages
      uses: actions/cache@v2
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
    - name: Build with Maven
      run: mvn clean package
          
    - uses: actions/upload-artifact@v1
      with:
        name: verademo.war
        path: target/verademo.war

  pipeline_scan:
    # needs the build step before this job will start running
    needs: build
    runs-on: ubuntu-latest
    name: pipeline scan

    steps:
      - name: checkout repo
        uses: actions/checkout@v2
      
      # get the compiled binary from a previous job
      - name: get archive
        uses: actions/download-artifact@v2
        with:
          name: verademo.war

      # run the pipeline scan action
      - name: pipeline-scan action step
        id: pipeline-scan
        uses: veracode/Veracode-pipeline-scan-action@pipeline-scan-beta-v0.0.3
        with:
          vid: ${{ secrets.VERACODE_API_ID }}
          vkey: ${{ secrets.VERACODE_API_KEY }}
          file: "verademo.war" 

  #import-issues:
    #needs: veracode-pipeline-scan
    #runs-on: ubuntu-latest
    #steps:
      #- name: get scan results
        #uses: actions/download-artifact@v2
        #with:
          #name: filtered-results

      #- name: import flaws as issues
        #uses: veracode/veracode-flaws-to-issues@v1
        #with:
          #scan-results-json: 'filtered_results.json'
          #github-token: ${{ secrets.GITHUB_TOKEN }}

  #veracode-sca-task:
    #runs-on: ubuntu-latest
    #name: Scan repository for Issues

    #steps:
      #- name: Checkout
        #uses: actions/checkout@v3
      #- name: Run Veracode SCA
        #env:
          #SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        #uses: veracode/veracode-sca@v1.09
        #with:
          #github_token: ${{ secrets.GITHUB_TOKEN }}
          #create-issues: true
